backend/api/urls.py
from django.urls import path
from .views import CreateUserView, LoginTemplateView, HomePageView, test
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'api'

urlpatterns = [
    path('user/register/', CreateUserView.as_view(), name='user-register'),
    path('user/login/', LoginTemplateView.as_view(), name='login-template'),
    
    path('token/', TokenObtainPairView.as_view(), name='user-login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='refresh-token'),
    path('home/', HomePageView.as_view(), name='home'),
    path('test/', test, name='test'),
    
]

backend/core/urls.py
from django.urls import path
from .views import welcome, my_personal_info, tool_menu, web_list, disclaimer


app_name = 'core'

urlpatterns = [
    path("", view=welcome, name='welcome'),
    path("personal info/", view=my_personal_info, name='my_personal_info'),
    path("Tool Menu/", view=tool_menu, name='tool_menu'),
    path("web list/", view=web_list, name='web_list'),
    path("disclaimer/", view=disclaimer, name='disclaimer'),
    ]

backend/report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('acc_report/', include('acc_report.urls')),
    path('api/', include('api.urls')),
    path('java/', include('java.urls')),
    path('list01/', include('list01.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/core/views.py
from django.shortcuts import render

def welcome(request):
    return render(request, template_name='welcome.html')


def my_personal_info(request):
    return render(request, 'my_personal_data.html')

def tool_menu(request):
    return render(request, 'tool_menu.html')

def web_list(request):
    return render(request, 'web_list.html')

def disclaimer(request):
    return render(request, 'disclaimer.html')

def copy_report(request):
    pass

backend/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Welcome{% endblock %}</title> <!--Welcome is Default Title-->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>

<header>
  <h1>
    <a href="{% url 'core:welcome' %}">PREK CHAK CUSTOMS AND EXCISE OFFICE</a>
  </h1>
    
  <nav>
    <ul>
      <li><a href="{% url 'core:welcome' %}">Home</a></li>
      <li><a href="{% url 'core:my_personal_info' %}">About</a></li>
      <li><a href="{% url 'core:disclaimer' %}">Tools</a></li>
      <li><a href="#">Chatbot</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="{% url 'core:web_list' %}">GDCE</a></li>
    </ul>
  </nav>

</header>

<main>
  {% block content %}
  {% endblock %} 
</main>
  
  <footer>
    <p>&copy; Developed by Mr. TOUCH DARA, 17th Generation Customs Official, ID: 1823. All Rights Reserved.</p>
  </footer>
  
</body>
</html>

backend/core/templates/disclaimer.html
{% extends 'base.html' %}


{% block content %}

    <h2>Welcome to KAM12 Report Automation.</h2>
    <h3><strong>Attention to Detail Required: Automated Process Advisory</strong></h3>
    <p>
Dear Guy, <br>

I would like to bring to your attention an important aspect regarding the automation process currently in development. While our automation endeavors aim to streamline operations and enhance efficiency, it's crucial to acknowledge that automated logic may encounter discrepancies and produce unexpected outcomes.
As the developer behind this automation initiative, I take responsibility for ensuring its reliability and effectiveness. However, given the inherent complexity of software development, there's a possibility that certain logic paths may not function as intended, leading to suboptimal results.
Therefore, I urge everyone involved to exercise caution and diligence when implementing and testing the automated processes. It's imperative to conduct thorough testing, validate outputs against expected outcomes, and promptly address any anomalies or errors encountered during the testing phase.
By fostering a culture of vigilance and collaboration, we can collectively mitigate risks associated with automation and work towards refining our processes for optimal performance and reliability.
<br><br>
Thank you for your attention to this matter.
<br><br>
Sincerely,
<br>
Dara TOUCH 
<br>
[GDCE_ID: 1823]
</p>

<a href="{% url 'core:tool_menu' %}" class="button">OK, Go to tools</a>

{% endblock %}

backend/core/templates/my_personal_data.html
{% extends 'base.html' %}

{% block title %}Personal Information{% endblock %}

{% block content %}

<section class="dara">
  <h2>My Personal Data</h2>

  <p>
        My name is TOUCH Dara, ID: 1823. I have worked as a customs official since 2015 at Prek Chak Customs And Excise Office (KAM12).
  </p>

</section>

{% endblock %}

backend/core/templates/tool_menu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Tool Menu{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

<div class="col-menu">
    
    <div class="menu">

        <a href="{% url 'acc_report:upload_form' %}" class="button">
            <div class="menu-item">
                <h3>Accounting Report</h3>
            </div>
        </a>

        <a href="#" class="button">
            <div class="menu-item">
                <h3>Admin Report</h3>
            </div>
        </a>

    </div>

    <div class="menu">

        <a href="#" class="button">
            <div class="menu-item">
                <h3>List01 Report</h3>
            </div>
        </a>

        <a href="#" class="button">
            <div class="menu-item">
                <h3>List07 Report</h3>
            </div>
        </a>
    </div>

    <div class="menu">
        <a href="{% url 'acc_report:download_acc_report_form' %}" class="button">
            <div class="menu-item">
                <h3>Accounting Report <br> <sub><sub></sub><sub>(Custom Excel Form)</sub></sub></sub></h3>
            </div>

        </a>
    </div>

    <div class="menu">
        <a href="#" class="button">
            <div class="menu-item">
                <h3>Others <br> <sub><sub></sub><sub>(Custom Excel Form)</sub></sub></sub></h3>
            </div>

        </a>
    </div>
</div>

{% endblock %}

backend/core/templates/web_list.html
{% extends 'base.html' %}

{% block title %}Related Web{% endblock %}

{% block content %}
<body>
    <ul>
        <li style="margin-bottom: 10px;">
            <a href="https://mef.gov.kh/">MEF Cambodia</a>
        </li>
        <li style="margin-bottom: 10px;">
            <a href="https://customs.gov.kh/">GDCE Cambodia</a>
        </li>
        <li style="margin-bottom: 10px;">
            <a href="https://apps.customs.gov.kh/login">E-Customs</a>
        </li>
        <li style="margin-bottom: 10px;">
            <a href="https://www.tax.gov.kh/km">GDT Cambodia</a>
        </li>
    </ul>        
</body>
{% endblock %}

backend/core/templates/welcome.html
{% extends 'base.html' %}

{% block content %}
<body>
  <h2>Welcome to Our Website</h2>
  
  <p>Prek Chak is an international border checkpoint between Cambodia and Vietnam, located Tkov Village, Ruesei Srok Kanglech Commune, Kampong Trach District, Kampot Province.<br>
    Prek Chak Customs and Excise Office is responsible for processing travelers entering and exiting Cambodia, including collecting customs duties and taxes on imported goods.</p>
  <a href="#" class="button">Learn More</a>

  <section class="about">
    <h3>About Us</h3>
    <p>Preck Chak Customs And Excise Office located in Tkov Village, Reusei Srok Kang Lech Commune, Kampong Trach District, Kampot Province.
      Its main role is collect tax and duties of import and export goods accross the border.
    </p>
  </section>

  <section class="services">
    <h3>Our Services</h3>
    <ul>
      <li>Service 1 Description</li>
      <li>Service 2 Description</li>
      <li>Service 3 Description</li>
    </ul>
  </section>
</body>

{% endblock %}