backend/api/urls.py
from django.urls import path
from .views import CreateUserView, LoginTemplateView, HomePageView, test
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'api'

urlpatterns = [
    path('user/register/', CreateUserView.as_view(), name='user-register'),
    path('user/login/', LoginTemplateView.as_view(), name='login-template'),
    
    path('token/', TokenObtainPairView.as_view(), name='user-login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='refresh-token'),
    path('home/', HomePageView.as_view(), name='home'),
    path('test/', test, name='test'),
    
]

backend/list01/urls.py
from django.urls import path
# from .views import List01ViewSet
from .views import List01View, SalakabattDataView, DownloadSalakabattDataView, ListCleanUp, List01MakeUpView
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import View

app_name = 'list01'


urlpatterns = [
    path('', List01View.as_view(), name='create_list01'),
    path('salakabatt-data', SalakabattDataView.as_view(), name='salakabatt_data'),
    path('download-salakabatt-data', DownloadSalakabattDataView.as_view(), name='download_salakabatt_data'),
    path('cleanup', ListCleanUp.as_view(), name='cleanup'),
    path('makeup-list01-template', List01MakeUpView.as_view(), name='makeup_list01_template'),
]

backend/report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('acc_report/', include('acc_report.urls')),
    path('api/', include('api.urls')),
    path('java/', include('java.urls')),
    path('list01/', include('list01.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/list01/models.py
from django.db import models

# Create your models here.

backend/list01/views.py
import shutil
import os
import glob
import pandas as pd
import openpyxl
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.http import FileResponse

from baseoperations.kam12list01.list01 import List01
from baseoperations.kam12list01.salakabatt import AllSalakabatt


class List01View(View):
    """
    View to handle file uploads and generate a downloadable Excel file.
    Methods:
        get(request, *args, **kwargs):
            Renders the index.html template.
        post(request, *args, **kwargs):
            Handles the file upload, processes the files, and returns a downloadable Excel file.
    Attributes:
        None
    """
    salakabatt_files = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    office_choices = {
        'KAM11': 'ការិយាល័យគយនិងរដ្ឋាករតន់ហន់',
        'KAM12': 'ការិយាល័យគយនិងរដ្ឋាករព្រែកចាក',
        'KAM16': 'ការិយាល័យគយនិងរដ្ឋាករកំពង់ផែអន្តរជាតិព្រែកត្នោត',
        'KAM17': 'ការិយាល័យគយនិងរដ្ឋាករកំពង់ផែអន្តរជាតិខេត្តកំពត',
    }

    def get(self, request, *args, **kwargs):
        return render(request, 'index.html', {
            'salakabatt_files': self.salakabatt_files, 
            'office_choices': self.office_choices
            })

    def post(self, request, *args, **kwargs):
        sad_detail = request.FILES.get('sad_detail')
        budget = request.FILES.get('budget')
        salakabatt_files = [request.FILES.get(f'salakabatt_for_{month}') for month in self.salakabatt_files]
        reporter_name = request.POST.get('reporter_name')
        office_code_key = request.POST.get('office_code')
        
        
        # Copy the template file to a new file
        list01_template = os.path.join(settings.BASE_DIR, 'staticfiles', 'excel', 'xlsx', 'List01_Template.xlsx')
        list01_copy = os.path.join(settings.BASE_DIR, 'staticfiles', 'excel', 'xlsx', 'List01.xlsx')
        os.makedirs(os.path.dirname(list01_copy), exist_ok=True)
        shutil.copy2(list01_template, list01_copy)

        # Create a temporary directory to store the uploaded files (salakabatt)
        temp_dir = os.path.join(settings.BASE_DIR, 'temp', 'list01')
        temp_dir_sad_and_budget = os.path.join(settings.BASE_DIR, temp_dir, 'list01', 'sad_and_budget')
        temp_dir_salakabatt = os.path.join(settings.BASE_DIR, temp_dir, 'list01', 'salakabatt')
        os.makedirs(temp_dir_sad_and_budget, exist_ok=True)
        os.makedirs(temp_dir_salakabatt, exist_ok=True)

        sad_detail_path = os.path.join(temp_dir_sad_and_budget, 'sad_detail.xlsx')
        budget_path = os.path.join(temp_dir_sad_and_budget, 'budget.xlsx')

        # Delete .xlsx files in the temp_dir_salakabatt directory
        existing_files = glob.glob(os.path.join(temp_dir_salakabatt, '*.xlsx'))
        for file_path in existing_files:
            os.remove(file_path)

        # Save salakabatt files to the temp_dir_salakabatt directory
        for i, file in enumerate(salakabatt_files, start=0):
            if file:
                file_path = os.path.join(temp_dir_salakabatt, f'{file.name}')
                with open(file_path, 'wb+') as destination:
                    for chunk in file.chunks():
                        destination.write(chunk)

        # Save the SAD_Detail and Budget uploaded files to the tem_dir_sad_and_budget directory
        with open(sad_detail_path, 'wb+') as destination:
            for chunk in sad_detail.chunks():
                destination.write(chunk)
        with open(budget_path, 'wb+') as destination:
            for chunk in budget.chunks():
                destination.write(chunk)

        salakabatt_files = glob.glob(os.path.join(temp_dir_salakabatt, '*.xlsx'))

        list01 = List01(
            template_file=list01_copy, 
            budget_file=budget_path, 
            sad_detail_file=sad_detail_path, 
            list_of_salakabatt_path=salakabatt_files
            )
        
        list01.write(reporter_name=reporter_name, office_choice=self.office_choices.get(office_code_key, ''))

        # Serve the file as a downloadable response
        response = FileResponse(open(list01_copy, 'rb'), as_attachment=True, filename='List01.xlsx')
        response['Content-Disposition'] = 'attachment; filename="List01.xlsx"'

        return response


class SalakabattDataView(View):
    file_labels = ['File 1', 'File 2', 'File 3', 'File 4', 'File 5', 'File 6', 'File 7', 'File 8', 'File 9', 'File 10', 'File 11', 'File 12']
    
    def get(self, request, *args, **kwargs):
        return render(request, 'salakabatt.html', {'file_labels': enumerate(self.file_labels, start=1)})

    def post(self, request, *args, **kwargs):
        # Get all uploaded files into a list
        files = [request.FILES.get(f'file{i}') for i in range(1, len(self.file_labels) + 1)]
        
        # Create the temp directory
        tem_dir = os.path.join(settings.BASE_DIR, 'temp', 'salakabatt')
        os.makedirs(tem_dir, exist_ok=True)  # Creates the directory if it doesn't exist

        existing_files = glob.glob(os.path.join(tem_dir, '*.xlsx'))
        for file_path in existing_files:
            os.remove(file_path)
        # Iterate over the files and save them with dynamic filenames
        for i, file in enumerate(files, start=1):
            if file:  # Check if the file exists
                file_path = os.path.join(tem_dir, f'file{i}.xlsx')
                with open(file_path, 'wb+') as destination:
                    for chunk in file.chunks():
                        destination.write(chunk)
        
        uploaded_files = glob.glob(os.path.join(tem_dir, '*.xlsx'))

        salakabatt = AllSalakabatt(uploaded_files)
        tax_data = salakabatt.tax_data
        non_tax_data = salakabatt.non_tax_data

        # Create an Excel file with 2 sheets: tax_data and non_tax_data
        output_file = os.path.join(tem_dir, 'salakabatt_data.xlsx')
        with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
            tax_data.to_excel(writer, sheet_name='Tax Data', index=False)
            non_tax_data.to_excel(writer, sheet_name='Non-Tax Data', index=False)
        
        # Save the path to the output file in the session or pass it as context
        request.session['output_file'] = output_file
        # Set a success message and redirect to the same page
        messages.success(request, "File has been successfully generated. Click the link below to download it.")

        return render(request, 'download.html')


class DownloadSalakabattDataView(View):
    def get(self, request, *args, **kwargs):
        # Get the file path from the session
        output_file = request.session.get('output_file')
        if output_file and os.path.exists(output_file):
            return FileResponse(open(output_file, 'rb'), as_attachment=True, filename='salakabatt_data.xlsx')
        else:
            messages.error(request, "File not found.")
        return render(request, 'salakabatt.html')

class ListCleanUp(View):
    CODES = ['VVP', 'VOP', 'SPP', 'SOP', 'CSF', 'TSF', 'TSP', 'TSS', 
             'TSC', 'TSM', 'TST', 'TSA', 'TSL', 'TSD', 'TSE', 'TSB', 
             'TSG', 'TSK', 'TSZ', 'TSR', 'TSQ', 'TSJ', 'TSN', 'TSO', 
             'TSP', 'TSV', 'TSW', 'TSX', 'TSY', 'TSZ', 'TSU']
    
    def get(self, request, *args, **kwargs):
        return render(request, 'cleanup_list01.html', {'codes':self.CODES})
    
    def post(self, request, *args, **kwargs):
        selected_codes = request.POST.getlist('codes')
        print(selected_codes)
        print(type(selected_codes))
        return render(request, 'cleanup_list01.html', {
            'codes': self.CODES,
            'selected_codes': selected_codes
        })
    
    # ជំហ៊ានបន្ទាប់ពីការជ្រើសរើសកូដដែលត្រូវបានជ្រើសរើស ត្រូវកំណត់ថា ដូចំណូលដែលមាននៅក្នុងselected_codes ត្រូវបានលុបចេញពីList01


class List01MakeUpView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'makeup_list01.html')

    def post(self, request, *args, **kwargs):
        single_sheet_tempalte = request.FILES.get('single_sheet_template')
        wb = openpyxl.load_workbook(single_sheet_tempalte)
        ws = wb.active
        ws.title = 'List01'
        for sheet in wb.worksheets:
            print(sheet.title)
        return render(request, 'makeup_list01.html')

backend/list01/templates/cleanup_list01.html
{% extends 'base.html' %}

{% block title %}Item List with Textboxes{% endblock %}

{% block content %}
<h1>List01 Cleanup</h1>
<style> 
    .checkbox-label { display: flex; align-items: center; margin-bottom: 8px; } 
    .checkbox-label input[type="checkbox"] { margin-right: 10px; width: 20px; height: 20px; /* Adjust size as needed */ } 
</style>

<form method="POST" action="{% url 'list01:cleanup' %}">
    {% csrf_token %}
    <label for="codes"> Select Code for Deleting </label>
    <ul id="codes">
        {% for code in codes %}
        <li class="checkbox-label">
            <input type="checkbox" id="code_{{ forloop.counter }}" name="codes" value="{{ code }}">
            <label for="code_{{ forloop.counter }}">{{ code }}</label>
        </li>
        {% endfor %}
    </ul>
    <button type="submit">Submit</button>
</form>

{% endblock %}

backend/list01/templates/download.html
{% extends 'base.html' %}
{% block title %} សាលាកប័ត្រ {% endblock %}
{% block content %}
<body>
    <h1>សាលាកប័ត្រ</h1>

    <!-- Display success messages -->
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <!-- Show download link if the file was generated -->
    {% if request.session.output_file %}
        <p><a href="{% url 'list01:download_salakabatt_data' %}" class="btn btn-success">Download File</a></p>
    {% endif %}
</body>
{% endblock %}

backend/list01/templates/index.html
{% extends 'base.html' %}

{% block title %} Create List01 {% endblock %}

{% block content %}

<h1>List01</h1>
<p>
    This form is designed for creating LIST01. 
    Please follow the instructions carefully to ensure the files you upload are correct and in the appropriate locations. 
    Once everything is ready, click the button to create LIST01, and it will be downloaded to your local machine in .xlsx format. 
    You will need to review the data and fill in some information manually.
</p>
<form method="POST" action="{% url 'list01:create_list01' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <!-- First Column -->
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="sad_detail" class="form-label">SAD Detail File</label>
                    <input type="file" name="sad_detail" id="sad_detail" class="form-control">
                </div>
                
                <div class="mb-3">
                    <label for="budget" class="form-label">Budget File</label>
                    <input type="file" name="budget" id="budget" class="form-control">
                </div>
                
                <div class="p-3 mb-2 bg-secondary text-white">
                    <div>
                        <label for="reporter_name">You Name</label>
                        <input type="text" name="reporter_name" id="reporter_name" placeholder="Your Full Name Here" class="form-control">
                    </div><br>

                    <div>
                        <label for="office_code">Select Office Code</label>
                        <select id="office_code" name="office_code"> 
                            {% for office_code, office_name in office_choices.items %} 
                                <option value="{{ office_code }}">{{ office_code }}</option> 
                            {% endfor %} 
                        </select>
                    </div>
                </div>
            </div>

            <!-- Second Column -->
            <div class="col-md-6">
                <p>Make sure you uploaded Deika Samrong Salakbatt for each month here<p></p>
                {% for file in salakabatt_files %}
                    <div class="mb-3">
                        <label for="salakabatt_for_{{file}}" class="form-label">File for {{file}}</label>
                        <input type="file" name="salakabatt_for_{{file}}" id="salakabatt_for_{{file}}" class="form-control">
                    </div>
                {% endfor %}
            </div>
            
            <div class="mt-4">
                <p>Everything are OK ? <br> If YES, Please click
                    <button type="submit" class="btn btn-primary">Create List01</button>
                    to create the LIST01.
                </p>
            </div>
        </div>
    </div>
</form>

<div id="success-message" class="mt-3" style="display: none;">
    <div class="alert alert-success">File processed successfully</div>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

backend/list01/templates/makeup_list01.html
{% extends 'base.html' %}
{% block title %} Makeup Template List01 {% endblock %}
{% block content %}
<body>
    <h1>Make Up Template List01</h1>
    <form method="POST" action="{% url 'list01:makeup_list01_template' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="btn btn-primary">
            <label for="single_sheet_template">List01 Single Sheet Template</label>
            <input type="file" name="single_sheet_template" id="single_sheet_template">
        </div>        
        <button type="submit">Create List01 Template</button>
    </form>
</body>
{% endblock %}

backend/list01/templates/salakabatt.html
{% extends 'base.html' %}
{% block title %} សាលាកប័ត្រ {% endblock %}
{% block content %}
<body>
    <h1>សាលាកប័ត្រ</h1>
    <form method="POST" action="{% url 'list01:salakabatt_data' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% for index, label in file_labels %}
        <div class="btn btn-primary">
            <label for="file{{ index }}">{{ label }}</label>
            <input type="file" name="file{{ index }}" id="file{{ index }}">
        </div>        
        {% endfor %}
        <button type="submit">Process For Data</button>
    </form>
</body>
{% endblock %}